services:
  db:
    image: postgis/postgis:15-3.3-alpine # Imagen oficial con PostGIS
    container_name: exq_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: exq_nestjs_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: